WIP: works on Linux but Windows
 Error: [FMUCHK] FMU logger callback does not propagate component environment to the application
	[FMU][FMU status:Fatal] Unable to instantiate a new instance of 'no.ntnu.ais.fmu4j.slaves.Identity'!
[FATAL][FMUCHK] Could not instantiate the model
C:\Users\RUNNER~1\AppData\Local\Temp\fmucktmpa00608\RESOUR~1\model.jar - The process cannot access the file because it is being used by another process.